### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by MingleiGitHub** [hhexiy/scip-dagger#2]
Dear He,
I am trying to install the scip-dagger but I have encountered some problems and may need your help.

The link you've provided for the modified scip sources is outdated now, do you have other backup repos for them? If not, could you provide some suggestions on how to make the changes as required?

Besides, the LIBLINEAR-weights link is also outdated, could you also help on that?

Thank you for your time.

Best regards,
Ming

**Comment by hhexiy** [comment]
Hi, I've updated the README.

**Comment by MingleiGitHub** [comment]
Hi He He,

Many thanks for the updates! I am having trouble to build the scip 3.1.0, could you provide some suggestions on it? The new version of the recommended CPLEX(v12.9) has changed some embedded functions which cannot compile through for the scip 3.1.0 version. But the old version of the CPLEX is not available from the IBM. I have tried many other scip 3.1.0 supported LP solvers, including 
soplex (v1.4.0, v1.7.0, v2.0.0, v3.0.0 and v4.0.1), gurobi7.0.2, mosek, but they all failed either cannot be build or with errors during scip compiling. 

Do you have any suggestions on the potential LP solvers that can be used to build the scip 3.1.0?

Thanks,
Ming

**Comment by GregorCH** [comment]
Are you sure that the old CPLEX version is not available anymore? You can probably request it from IBM support. I am not surprised that Gurobi and Mosek are not working out of the box. Note that the Gurobi interface has reached alpha status more recently, but was not fully working in SCIP 3.1.0.

As for SCIP 3.1.0, you can see from the web page that it was released as a bundle with SoPlex 2.0.0, so this setup should **definitely** work. If it does not work for you, please be more precise about the actual compilation steps, and the precise error message.

**Comment by MingleiGitHub** [comment]
Dear GregorCH,
Thanks for the reply. I have contacted the IBM and they refuse to provide any other version of CPLEX since I am an academic user. 

As for SoPlex 2.0.0, it has a static link to zlib 1.2.8 and GMP 5.0.5. I am having trouble in installing zlib 1.2.8 since once I make and install this lib, the ubuntu system (18.04) gui will crash. It seems the zlib is already a dependency of some ubuntu os libs. 

Soplex 4.0.1 can be installed via cmake method, but it seems there are mismatched parameters/functions with the scip 3.1.0 version as follows:
#############################################################################
##############################################################################
 $ make LPS=spx2
-> generating necessary links
- creating directory "lib/zimplinc"
- Current settings: LPS=spx2 OSTYPE=linux ARCH=x86_64 COMP=gnu SUFFIX= ZIMPL=true ZIMPLOPT=opt IPOPT=false IPOPTOPT=opt EXPRINT=cppad GAMS=false
...
-> compiling obj/O.linux.x86_64.gnu.opt/lib/lpi/lpi_spx2.o
src/lpi/lpi_spx2.cpp: In member function ‘virtual soplex::SPxSolver::Status SPxSCIP::doSolve(bool)’:
src/lpi/lpi_spx2.cpp:465:26: error: ‘verbose’ is not a member of ‘soplex::Param’
       verbosity = Param::verbose();
            
src/lpi/lpi_spx2.cpp:466:14: error: ‘setVerbose’ is not a member of ‘soplex::Param’
       Param::setVerbose(getLpInfo() ? SOPLEX_VERBLEVEL : 0);
...
rc/lpi/lpi_spx2.cpp:2053:56: error: ‘ALGORITHM_LEAVE’ is not a member of ‘soplex::SoPlex’
       lpi->spx->setIntParam(SoPlex::ALGORITHM, SoPlex::ALGORITHM_LEAVE);
...
Makefile:935: recipe for target 'obj/O.linux.x86_64.gnu.opt/lib/lpi/lpi_spx2.o' failed
make[1]: *** [obj/O.linux.x86_64.gnu.opt/lib/lpi/lpi_spx2.o] Error 1
Makefile:576: recipe for target 'libs' failed
make: *** [libs] Error 2
############################################################################
############################################################################
For the soplex 1.4.0, I failed to compile this lib, which gives compiling error at the end.

$ make COMP=gnu OPT=opt
-> compiling obj/O.linux.x86_64.gnu.opt/lib/changesoplex.o
...
-> compiling obj/O.linux.x86_64.gnu.opt/lib/mpsinput.o
src/mpsinput.cpp: In member function ‘bool soplex::MPSInput::readLine()’:
src/mpsinput.cpp:75:52: error: no match for ‘operator==’ (operand types are ‘std::basic_istream<char>::__istream_type {aka std::basic_istream<char>}’ and ‘int’)
          if (m_input.getline(m_buf, sizeof(m_buf)) == 0)
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
src/mpsinput.cpp:75:52: note: candidate: operator==(int, int) <built-in>
src/mpsinput.cpp:75:52: note:   no known conversion for argument 1 from ‘std::basic_istream<char>::__istream_type {aka std::basic_istream<char>}’ to ‘int’
In file included from /usr/include/c++/7/bits/locale_conv.h:41:0,
                 from /usr/include/c++/7/locale:43,
                 from /usr/include/c++/7/iomanip:43,
                 from src/spxlp.h:26,
                 from src/mpsinput.h:23,
                 from src/mpsinput.cpp:28:
...
src/mpsinput.cpp:75:55: note:   ‘std::basic_istream<char>::__istream_type {aka std::basic_istream<char>}’ is not derived from ‘const std::fpos<_StateT>’
          if (m_input.getline(m_buf, sizeof(m_buf)) == 0)
                                                       ^
Makefile:251: recipe for target 'obj/O.linux.x86_64.gnu.opt/lib/mpsinput.o' failed
make: *** [obj/O.linux.x86_64.gnu.opt/lib/mpsinput.o] Error 1

Any suggestion? Thank you for your time!
Regards,
Ming


> Are you sure that the old CPLEX version is not available anymore? You can probably request it from IBM support. I am not surprised that Gurobi and Mosek are not working out of the box. Note that the Gurobi interface has reached alpha status more recently, but was not fully working in SCIP 3.1.0.
> 
> As for SCIP 3.1.0, you can see from the web page that it was released as a bundle with SoPlex 2.0.0, so this setup should **definitely** work. If it does not work for you, please be more precise about the actual compilation steps, and the precise error message.

**Comment by GregorCH** [comment]
I am also using Ubuntu 18.04. Unfortunately, I cannot really help on the above issues you are experiencing. SoPlex and SCIP evolve together, so it is not surprising to me that the newest SoPlex does not compile with the older SCIP anymore. Compiling SoPlex should work with any reasonable version of Zlib.

I would not go through the hassle and compile SoPlex and SCIP individually.
Instead, here is my suggestion. I just tried it and it works out of the box for me:

1. Download the [SCIP Optimization Suite 3.1](https://scip.zib.de/download.php?fname=scipoptsuite-3.1.0.tgz).
2. `tar xf scipoptsuite-3.1.0.tgz`
3. `cd scipoptsuite-3.1.0`
4. `make`
5. (optional) repeat after installing eventually missing libraries.

In scipoptsuite-3.1.0/scip/src, you can afterwards make the necessary adjustments to enable scip-dagger.

**Comment by MingleiGitHub** [comment]
Many thanks for the detailed instructions! The suggested installation via scip suite works on my side too, and I have now installed the required SCIP 3.1.0. It passes the "make test". 

I have also compiled the liblinear and weight versions, but I think I will need your further guidance on how to compile the scipdagger.  

What I have done is as follows:
1. download the modified scip folder from the given repo.
2. use this modified scip folder to replace the  /test/scipoptsuite-3.1.0/scip-3.1.0/src/scip folder.
3. download the scip-dagger and put it in the dir parallel with scipoptsuite as /test/scip-dagger
4. rename the "train" built from liblinear-weights to "train-w", copy it with "train" and "predict" built from liblinear to the /test/scipoptsuite-3.1.0/scip-3.1.0/bin
5. run "make" in the /test/scip-dagger

But I have encountered the errors as presented later. I can see these sources are in /test/scip-dagger/src, but if I put them to scipoptsuite-3.1.0/scip-3.1.0/src, the error info is still the same. And with the changed  /test/scipoptsuite-3.1.0/scip-3.1.0/src/scip, re-compile the scip 3.1.0 using make under  /test/scipoptsuite-3.1.0/scip-3.1.0 folder gives similar failed message. Any suggestions?

Thank you for your time and help!


#############################################################################
The error message with "make" under scipdagger dir
-> linking bin/scipdagger.linux.x86_64.gnu.opt.spx
obj/O.linux.x86_64.gnu.opt/cmain.o: In function `main':
cmain.c:(.text.startup+0xe6e): undefined reference to `SCIPprintMyStatistics'
cmain.c:(.text.startup+0x10a8): undefined reference to `SCIPgetNodepru'
cmain.c:(.text.startup+0x10bc): undefined reference to `SCIPnodepruGetName'
obj/O.linux.x86_64.gnu.opt/nodesel_oracle.o: In function `nodeselExitOracle':
nodesel_oracle.c:(.text+0x6f): undefined reference to `SCIPfreeSolSelf'
obj/O.linux.x86_64.gnu.opt/nodesel_oracle.o: In function `SCIPreadOptSol.part.2'
...
nodepru_policy.c:(.text+0x3eb): undefined reference to `SCIPsetNodepruFree'
collect2: error: ld returned 1 exit status
Makefile:145: recipe for target 'bin/scipdagger.linux.x86_64.gnu.opt.spx' failed
make: *** [bin/scipdagger.linux.x86_64.gnu.opt.spx] Error 1

######################################################################
The error message with "make" to re-compile the scip-3.1.0

-> generating library lib/libnlpi.cppad-3.1.0.linux.x86_64.gnu.opt.a
-> compiling obj/O.linux.x86_64.gnu.opt/bin/cppmain.o
-> linking bin/scip-3.1.0.linux.x86_64.gnu.opt.spx
obj/O.linux.x86_64.gnu.opt/lib/scip/scip.o: In function `SCIPincludeNodepru':
scip.c:(.text+0x8b92): undefined reference to `SCIPnodepruCreate'
obj/O.linux.x86_64.gnu.opt/lib/scip/scip.o: In function `SCIPincludeNodepruBasic':
scip.c:(.text+0x8cc9): undefined reference to `SCIPnodepruCreate'
obj/O.linux.x86_64.gnu.opt/lib/scip/scip.o: In function `SCIPsetNodepruCopy':
...
obj/O.linux.x86_64.gnu.opt/lib/scip/solve.o: In function `SCIPsolveCIP':
solve.c:(.text+0xba6d): undefined reference to `SCIPnodepruPrune'
collect2: error: ld returned 1 exit status
build failed with READLINE=true: if readline is not available, try building with READLINE=false
build failed with ZLIB=true: if ZLIB is not available, try building with ZLIB=false
build failed with GMP=true: if GMP is not available, try building with GMP=false (note that this will deactivate Zimpl support)


#######################################################################


> I am also using Ubuntu 18.04. Unfortunately, I cannot really help on the above issues you are experiencing. SoPlex and SCIP evolve together, so it is not surprising to me that the newest SoPlex does not compile with the older SCIP anymore. Compiling SoPlex should work with any reasonable version of Zlib.
> 
> I would not go through the hassle and compile SoPlex and SCIP individually.
> Instead, here is my suggestion. I just tried it and it works out of the box for me:
> 
> 1. Download the [SCIP Optimization Suite 3.1](https://scip.zib.de/download.php?fname=scipoptsuite-3.1.0.tgz).
> 2. `tar xf scipoptsuite-3.1.0.tgz`
> 3. `cd scipoptsuite-3.1.0`
> 4. `make`
> 5. (optional) repeat after installing eventually missing libraries.
> 
> In scipoptsuite-3.1.0/scip/src, you can afterwards make the necessary adjustments to enable scip-dagger.

**Comment by mkaan96** [comment]
@mingleiyou1988 I have the same problem, did you ever resolve it?

**Comment by mkaan96** [comment]
I fixed it by replacing scip-3.1.0 in scipoptsuite-3.1.0 by the provided in the repo scip-3.1.0.tgz (extracted), compiling scipoptsuite-3.1.0 and lastly compiling SCIP-dagger

**Comment by hagianga21** [comment]
@mkaan96 Have you solved the problem with the CPLEX version?

**Comment by mkaan96** [comment]
@hagianga21 I asked IBM to send me CPLEX v12.6 and they did. I did mention I needed it to reproduce this work for my Masters thesis.

**Comment by hagianga21** [comment]
@mkaan96 and it works with this repo? Wait, it 's not free trial version?

**Comment by mkaan96** [comment]
@hagianga21 CPLEX is free for academics, but you can normally only obtain the current version. I had to request the old version personally
